### PR TITLE
feat: use mjs file extensions with type module

### PR DESCRIPTION
**Pull request by ericdeansanchez**

### CODE REVIEW

**Review by frederickfogerty — APPROVED** [review]
🔥🔥🔥

**Comment by frederickfogerty** [comment]
@ericdeansanchez what has it been like using `.mjs` and the module system overall in the new version of Node? I've never used `.mjs` directly so I'm wondering what the experience was like

**Comment by ericdeansanchez** [comment]
@frederickfogerty it's been smooth so far, tbh I haven't used them much either (just in this project). I also haven't seen a lot of projects using them explicitly (looked through more than a few `package.json` files from other projects haha).

**Pull request merged**
